name: flutter_native_badge
description: Flutter plugin for setting the badge count on native platforms.
  Wraps the native APIs for iOS and macOS to set the badge count on the app icon.
repository: https://github.com/isaacadariku/flutter_native_badge
issue_tracker: https://github.com/isaacadariku/flutter_native_badge/issues
version: 1.0.5

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_badge_foundation: ^1.0.4
  flutter_native_badge_platform_interface: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        default_package: flutter_native_badge_foundation
      macos:
        default_package: flutter_native_badge_foundation

scripts: derry.yaml
